name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # v1.4.6
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn setup
    - run: yarn build
    - run: yarn lint
    - run: yarn test
  all-jobs-pass:
    name: All jobs pass
    runs-on: ubuntu-20.04
    needs:
      - build-test
    steps:
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0